sonar.projectName=Expense Tracker App
sonar.sources=backend,frontend/src

# Test and coverage inputs
sonar.tests=backend,frontend/src
sonar.test.inclusions=**/*test*.py,**/*_test.py,**/*.spec.js,**/*.test.js,**/*.spec.jsx,**/*.test.jsx
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.svg,**/dist/**,**/build/**,terraform/**,k8s/**,screenshots/**
