apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: expense-tracker
data:
  POSTGRES_DB: expenses
  REACT_APP_API_URL: http://backend-service:5000
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: expense-tracker
  annotations:
    checkov.io/skip1: CKV_SECRET_6=Base64 High Entropy String is acceptable for demo environment
    checkov.io/skip2: CKV_SECRET_4=Basic Auth Credentials is acceptable for demo environment
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: pass
  SECRET_KEY: supersecretkey
  JWT_SECRET_KEY: superjwtkey
  DATABASE_URL: postgresql://user:pass@postgres-service:5432/expenses
